### ISSUE TITLE
Recursive subdirectory support

### ISSUE THREAD

**Issue by ww9** [hajimehoshi/file2byteslice#4]
I understand and support your decision @hajimehoshi of not merging #3. Keeping things simple is an art.

However I needed a similar tool which supports recursive sub directory scanning so I made https://github.com/ww9/file2go:

![image](https://user-images.githubusercontent.com/27555162/86519038-e9360680-be04-11ea-9361-02a7a5ea73c6.png)

I figured I would post this here if anyone needs so they don't ask you for this functionality. You're in the credits by the way: https://github.com/ww9/file2go

**Comment by hajimehoshi** [comment]
Thank you for including me in the credits!
